"""Reusable, host-independent core for Tennis Booker."""

from .config import Config, SGT
from .contracts import (
    Availability,
    AvailabilitySlot,
    BookingTarget,
    SCHEDULE_STATUSES,
    ScheduleRecord,
    bearer_tokens_from_har,
    booking_payload,
    normalize_bearer_token,
    parse_availability_payload,
)
from .domain import (
    build_rebooking_batch,
    build_schedule_record,
    display_datetime,
    filter_active_tennis_bookings,
    normalized_event_day,
    parse_event_day,
    release_at,
    schedule_booking_targets,
    schedule_event_times,
    single_target_schedule,
    validate_event_time,
)
from .errors import (
    APIError,
    AuthenticationError,
    BookerError,
    CancellationError,
    ClientUpgradeRequiredError,
    ConnectivityError,
    InputError,
    NetworkTimeoutError,
    PartialBookingError,
    RateLimitError,
    RebookingSubmissionError,
    StoreError,
    SystemError,
)

__all__ = [
    "APIError",
    "AuthenticationError",
    "Availability",
    "AvailabilitySlot",
    "BookerError",
    "BookingTarget",
    "CancellationError",
    "ClientUpgradeRequiredError",
    "Config",
    "ConnectivityError",
    "InputError",
    "NetworkTimeoutError",
    "PartialBookingError",
    "RateLimitError",
    "RebookingSubmissionError",
    "SCHEDULE_STATUSES",
    "SGT",
    "ScheduleRecord",
    "StoreError",
    "SystemError",
    "bearer_tokens_from_har",
    "booking_payload",
    "build_rebooking_batch",
    "build_schedule_record",
    "display_datetime",
    "filter_active_tennis_bookings",
    "normalize_bearer_token",
    "normalized_event_day",
    "parse_availability_payload",
    "parse_event_day",
    "release_at",
    "schedule_booking_targets",
    "schedule_event_times",
    "single_target_schedule",
    "validate_event_time",
]
